name: Build Rules PDF
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_latex:
    name: Build LaTeX document
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
          unzip fonts.zip
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v3
        with:
          scheme: full
          extra_fonts: |
            ./fonts/*.ttf  
          run: |
            (lualatex -synctex=1 -interaction=nonstopmode -shell-escape rules.tex || return 0) && \
            (lualatex -synctex=1 -interaction=nonstopmode -shell-escape rules.tex || return 0)
      - name: Add new release tag
        if: always()
        run: |
          git tag release-${{ env.RELEASE_DATE }} && git push origin -f refs/tags/release-${{ env.RELEASE_DATE }}
      - name: Release
        if: always()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ env.RELEASE_DATE }}
          files: rules.pdf
