name: Build Rules PDF
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_latex:
    name: Build LaTeX document
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          package_file: tl_packages
      - name: Add fonts
        run: |
          unzip fonts.zip && \
            mv fonts/* /usr/share/fonts/extra_fonts/ && \
            fc-cache -fv && \
            fc-list | sort
      - name: First pass
        run: lualatex -synctex=1 -interaction=nonstopmode -shell-escape rules.tex  
      - name: Second pass
        run: lualatex -synctex=1 -interaction=nonstopmode -shell-escape rules.tex  
      - name: Add new release tag
        if: always()
        run: |
          git tag release-${{ env.RELEASE_DATE }} && git push origin -f refs/tags/release-${{ env.RELEASE_DATE }}
      - name: Release
        if: always()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ env.RELEASE_DATE }}
          files: rules.pdf
