name: Build Rules PDF
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_latex:
    name: Build LaTeX document
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: rules.tex
          compiler: lualatex
          args: -synctex=1 -interaction=nonstopmode -shell-escape
          extra_font_packages: fonts
      - name: Release
        if: always()
        uses: softprops/action-gh-release@v2
        with:
          files: rules.pdf
